version: "3"

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - app-tier
  db:
    build: ./postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - app-tier
  spark:
    build: ./spark 
    command: ["spark-shell"] 

networks:
  app-tier:
    driver: bridge