
FROM apache/spark-py:latest
# FROM openjdk:11-jre-slim

# ENV SPARK_HOME /opt/spark


# RUN apt-get update && apt-get install -y curl && \
#     curl -L https://www.apache.org/dyn/closer.lua/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz | tar -xvf -C /opt && \
#     ln -s /opt/spark-3.2.0-bin-hadoop3.2 $SPARK_HOME && \
#     rm -rf /var/lib/apt/lists/*


# ENV PATH $SPARK_HOME/bin:$PATH
